### ISSUE TITLE
Fix `unchecked_unwraped` in `Box`

### ISSUE THREAD

**Issue by TimDiekmann** [TimDiekmann/alloc-wg#15]

**Comment by 95th** [comment]
`unwrap_unchecked` =)

Also, what do you mean by "fix"? Should those go away?

**Comment by TimDiekmann** [comment]
However ;)

It's a bug that was introduced when removing the `Error = !` bound.

**Comment by TimDiekmann** [comment]
I havn't fixed it yet as #16 will fix this anyway.
