### ISSUE TITLE
MemoryBlock::init is unsound

### ISSUE THREAD

**Issue by lachlansneff** [TimDiekmann/alloc-wg#19]
https://github.com/TimDiekmann/alloc-wg/blob/75c657273303773fd7383a1fc3fb21a331d3fad6/src/alloc.rs#L27-L44

Since the `ptr` field is public, you could put a bogus pointer in there, or even a pointer to an actual value, and then overwrite it with zeros or undefined bytes without using unsafe.

```rust
MemoryBlock {
    ptr: NonNull::new(ptr::null_mut()).unwrap(),
    size: usize::max(),
}.init(AllocInit::Zeroed);
```

**Comment by TimDiekmann** [comment]
As currently `alloc_wg::alloc` is the same as `core::alloc`, this crates now uses `core:alloc` instead, where this bug is fixed (`init` and `init_offset` are marked as `unsafe`). Thanks for reporting!
