### ISSUE TITLE
Badges also take pull requests into account

### ISSUE THREAD

**Issue by TimDiekmann** [TimDiekmann/alloc-wg#3]
I never have used GitHub actions before. I'd like to keep the badge in the readme, but the badges also takes pull requests into account. Currently, there are two actions, which are executed on both, a push and a pull request: `Lint`, `Test`. Does anyone is aware of a solution, only link the push action in the readme?

The current links are
```
https://github.com/TimDiekmann/alloc-wg/workflows/Test/badge.svg
https://github.com/TimDiekmann/alloc-wg/workflows/Lint/badge.svg
```

**Comment by 95th** [comment]
I think it will be:
```
https://github.com/TimDiekmann/alloc-wg/workflows/Test/badge.svg?event=push
```

**Comment by TimDiekmann** [comment]
Ah thanks, this works!
